steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
options:
  # in updated version of GCP, seems you need to specify where you want the build logs to be placed. 
  # read here: https://cloud.google.com/build/docs/securing-builds/store-manage-build-logs#:~:text=By%20default%2C%20Cloud%20Build%20stores,user%2Dcreated%20Cloud%20Storage%20bucket.
  logging: CLOUD_LOGGING_ONLY 
